Update podcast-feed-opus.rss
nextcloud/nextcloud.com pull request #1456
Opened 2021-02-25 10:48 UTC by cartierbresson

@ltsavar & @jospoortvliet 🥇

2021-02-25 10:57 UTC, ltsavar requested changes
2 little things...

2021-02-25 10:57 UTC, ltsavar commented on podcast-feed-opus.rss
> +      <description>In this eight-episode, our host Ingo talked with Arthur, the Senior Software Engineer at Nextcloud about Nextcloud Flow. Nextcloud Flow is the workflow engine of Nextcloud. </descr
</itunes:duration>

2021-02-25 10:57 UTC, ltsavar commented on podcast-feed-opus.rss
> +      <pubDate>Tue, 26 Feb 2021 9:00:00 GMT</pubDate>
Thu

2021-02-26 09:06 UTC, jospoortvliet requested changes

2021-02-26 09:06 UTC, jospoortvliet commented on podcast-feed-opus.rss
> +      <itunes:duration>00:25:39/itunes:duration>
```suggestion
      <itunes:duration>00:25:39</itunes:duration>
```

2021-02-26 09:06 UTC, jospoortvliet commented on podcast-feed-opus.rss
> +      <description>In this eight-episode, our host Ingo talked with Arthur, the Senior Software Engineer at Nextcloud about Nextcloud Flow. Nextcloud Flow is the workflow engine of Nextcloud. </descr
```suggestion
      <description>In this eight-episode, our host Ingo talked with Arthur, Senior Software Engineer at Nextcloud, about Nextcloud Flow. Nextcloud Flow is the workflow engine of Nextcloud. </description>
```

2021-02-26 09:06 UTC, jospoortvliet commented on podcast-feed-opus.rss
> +      <itunes:summary>In this eight-episode, our host Ingo talked with Arthur, the Senior Software Engineer at Nextcloud about Nextcloud Flow. Nextcloud Flow is the workflow engine of Nextcloud.
```suggestion
      <itunes:summary>In this eight-episode, our host Ingo talked with Arthur, Senior Software Engineer at Nextcloud. about Nextcloud Flow. Nextcloud Flow is the workflow engine of Nextcloud. 
```

2021-02-26 09:06 UTC, jospoortvliet commented on podcast-feed-opus.rss
> +      <pubDate>Tue, 26 Feb 2021 9:00:00 GMT</pubDate>
```suggestion
      <pubDate>Fri, 26 Feb 2021 9:00:00 GMT</pubDate>
```

2021-02-26 09:09 UTC, jospoortvliet approved these changes

2021-02-26 09:31 UTC, merged