Update podcast-feed.rss
nextcloud/nextcloud.com pull request #1457
Opened 2021-02-25 10:51 UTC by cartierbresson

@ltsavar & @jospoortvliet 🥇

2021-02-25 10:58 UTC, ltsavar approved these changes

2021-02-26 09:07 UTC, jospoortvliet requested changes

2021-02-26 09:07 UTC, jospoortvliet commented on podcast-feed.rss
> +      <itunes:subtitle>In this eight-episode, our host Ingo talked with Arthur, the Senior Software Engineer at Nextcloud about Nextcloud Flow.</itunes:subtitle>
```suggestion
      <itunes:subtitle>In this eight-episode, our host Ingo talked with Arthur, Senior Software Engineer at Nextcloud, about Nextcloud Flow.</itunes:subtitle>
```

2021-02-26 09:07 UTC, jospoortvliet commented on podcast-feed.rss
> +      <itunes:summary> In this eight-episode, our host Ingo talked with Arthur, the Senior Software Engineer at Nextcloud about Nextcloud Flow. Nextcloud Flow is the workflow engine of Nextcloud.
```suggestion
      <itunes:summary> In this eight-episode, our host Ingo talked with Arthur, Senior Software Engineer at Nextcloud, about Nextcloud Flow. Nextcloud Flow is the workflow engine of Nextcloud.
```

2021-02-26 09:07 UTC, jospoortvliet commented on podcast-feed.rss
> +      <pubDate>Thu, 26 Feb 2021 9:00:00 GMT</pubDate>
```suggestion
      <pubDate>Fri, 26 Feb 2021 9:00:00 GMT</pubDate>
```

2021-02-26 09:07 UTC, cartierbresson reviewed
ok!

2021-02-26 09:08 UTC, jospoortvliet approved these changes

2021-02-26 09:31 UTC, merged